# Generated by Django 3.2.7 on 2021-09-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cor1x', models.PositiveIntegerField()),
                ('cor1y', models.PositiveIntegerField()),
                ('cor1st', models.TimeField()),
                ('cor1ed', models.TimeField()),
                ('rate1', models.PositiveIntegerField()),
                ('reason1', models.TextField()),
                ('cor2x', models.PositiveIntegerField()),
                ('cor2y', models.PositiveIntegerField()),
                ('cor2st', models.TimeField()),
                ('cor2ed', models.TimeField()),
                ('rate2', models.PositiveIntegerField()),
                ('reason2', models.TextField()),
                ('cor3x', models.PositiveIntegerField()),
                ('cor3y', models.PositiveIntegerField()),
                ('cor3st', models.PositiveIntegerField()),
                ('cor3ed', models.TimeField()),
                ('rate3', models.PositiveIntegerField()),
                ('reason3', models.TextField()),
                ('gender', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('trans', models.TextField()),
            ],
        ),
    ]
