# Generated by Django 3.2.7 on 2021-09-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='depa',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='register',
            name='cor1ed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='cor1st',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='cor2ed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='cor2st',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='cor3ed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='cor3st',
            field=models.TextField(),
        ),
    ]
