# Generated by Django 3.2.7 on 2021-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_register_depa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='depa',
            field=models.TextField(default=None),
        ),
    ]
